version: '3.9'

services:
  bot:
    build:
      context: .
    restart: on-failure
    stop_signal: SIGINT
    command: python main.py
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./.:/app

  db:
    image: postgres:12-alpine
    restart: on-failure
    env_file:
      - .env
    volumes:
      - postgresql_volume:/var/lib/pgsql
    ports:
      - "5432:5432"


volumes:
  postgresql_volume:
