version: '3.9'

services:
  bot:
    build:
      context: .
    restart: on-failure
    stop_signal: SIGINT
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./.:/app

  postgres:
    image: postgres:12-alpine
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    volumes:
      - postgresql_volume:/var/lib/pgsql

volumes:
  postgres-data:
